default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mashup_db_dev
  host: localhost
  username: <%= Rails.application.credentials.dig(:db, :login) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

test:
  <<: *default
  database: mashup_db_test
  host: localhost
  username: <%= Rails.application.credentials.dig(:db, :login) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: mashup_db_production
  username: mashup_db
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
