default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials[:db][:login] %>
  password: <%= Rails.application.credentials[:db][:password] %>
  host: localhost

development:
  <<: *default
  database: mashup_db_dev

test:
  <<: *default
  database: mashup_db_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
